// Components - DUMMY DATA

export const componentList = [
  {
    id: 1,
    category: "Beverages",
    brand: "Coca-Cola",
    productName: "CocoCola",
    packSize: "200 ml",
    componentType: "Label Back",
    img: "coke",
    progressStatus: "In Progress",
    timeStatus: "Task due 37+ day(s) ago",
  },
  {
    id: 2,
    category: "Beverages",
    brand: "Coca-Cola",
    productName: "CocoCola",
    packSize: "600 ml",
    componentType: "Label Back",
    img: "coke",
    progressStatus: "In Progress",
    timeStatus: "Task due 47+ day(s) ago",
  },
  {
    id: 3,
    category: "Beverages",
    brand: "Coca-Cola",
    productName: "CocoCola",
    packSize: "1 Ltr",
    componentType: "Label Back",
    img: "coke",
    progressStatus: "In Progress",
    timeStatus: "Task due 23+ day(s) ago",
  },
  {
    id: 4,
    category: "Beverages",
    brand: "Parle",
    productName: "Frooti",
    packSize: "200 ml",
    componentType: "Label Back",
    img: "frooti",
    progressStatus: "In Progress",
    timeStatus: "Task due 6+ day(s) ago",
  },
  {
    id: 5,
    category: "Beverages",
    brand: "Parle",
    productName: "Frooti",
    packSize: "700 ml",
    componentType: "Label Back",
    img: "frooti",
    progressStatus: "In Progress",
    timeStatus: "Task due 25+ day(s) ago",
  },
  {
    id: 6,
    category: "Beverages",
    brand: "Parle",
    productName: "Frooti",
    packSize: "2 Ltr",
    componentType: "Label Back",
    img: "frooti",
    progressStatus: "In Progress",
    timeStatus: "Task due 34+ day(s) ago",
  },
  {
    id: 7,
    category: "Sweets",
    brand: "B-Cake",
    productName: "Cake",
    packSize: "250 gm",
    componentType: "Label Back",
    img: "cake",
    progressStatus: "In Progress",
    timeStatus: "Task due 24+ day(s) ago",
  },
  {
    id: 8,
    category: "Sweets",
    brand: "B-Cake",
    productName: "Cake",
    packSize: "500 gm",
    componentType: "Label Back",
    img: "cake",
    progressStatus: "In Progress",
    timeStatus: "Task due 11+ day(s) ago",
  },
  {
    id: 9,
    category: "Sweets",
    brand: "B-Cake",
    productName: "Cake",
    packSize: "1 kg",
    componentType: "Label Back",
    img: "cake",
    progressStatus: "In Progress",
    timeStatus: "Task due 20+ day(s) ago",
  },
  {
    id: 10,
    category: "Snacks",
    brand: "Lays",
    productName: "Chips",
    packSize: "40 gm",
    componentType: "Label Back",
    img: "chips",
    progressStatus: "In Progress",
    timeStatus: "Task due 19+ day(s) ago",
  },
  {
    id: 11,
    category: "Snacks",
    brand: "Lays",
    productName: "Chips",
    packSize: "80 gm",
    componentType: "Label Back",
    img: "chips",
    progressStatus: "In Progress",
    timeStatus: "Task due 4+ day(s) ago",
  },
  {
    id: 12,
    category: "Snacks",
    brand: "Lays",
    productName: "Chips",
    packSize: "120 gm",
    componentType: "Label Back",
    img: "chips",
    progressStatus: "In Progress",
    timeStatus: "Task due 12+ day(s) ago",
  },
  {
    id: 13,
    category: "Sweets",
    brand: "Choco",
    productName: "Chocolate",
    packSize: "10 gm",
    componentType: "Label Front",
    img: "chocolate",
    progressStatus: "In Progress",
    timeStatus: "Task due 27+ day(s) ago",
  },
  {
    id: 14,
    category: "Sweets",
    brand: "Choco",
    productName: "Chocolate",
    packSize: "50 gm",
    componentType: "Label Front",
    img: "chocolate",
    progressStatus: "In Progress",
    timeStatus: "Task due 9+ day(s) ago",
  },
  {
    id: 15,
    category: "Sweets",
    brand: "Choco",
    productName: "Chocolate",
    packSize: "100 gm",
    componentType: "Label Back",
    img: "chocolate",
    progressStatus: "In Progress",
    timeStatus: "Task due 10+ day(s) ago",
  },
  {
    id: 16,
    category: "Sweets",
    brand: "Choco",
    productName: "Chocolate",
    packSize: "200 gm",
    componentType: "Label Back",
    img: "chocolate",
    progressStatus: "In Progress",
    timeStatus: "Task due 17+ day(s) ago",
  }
];