// All Projects - DUMMY DATA

export const projectsListArray = [
  {
    id: 1,
    category: "Dairy",
    packSize: "200gm",
    requestNumber: "81P-1A",
    initiatedBy: "Designer",
    initiatedDate: "31-Jul-2020",
    product: "Butter",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 2,
    category: "Dairy",
    packSize: "500ml",
    requestNumber: "81P-1B",
    initiatedBy: "Approver",
    initiatedDate: "24-Jul-2020",
    product: "Milk",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 3,
    category: "Snacks",
    packSize: "500gm",
    requestNumber: "81P-1C",
    initiatedBy: "Approver",
    initiatedDate: "23-Jul-2020",
    product: "Maggie",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 4,
    category: "Dairy",
    packSize: "200gm",
    requestNumber: "81P-1D",
    initiatedBy: "Designer",
    initiatedDate: "19-Jul-2020",
    product: "Butter",
    componentType: "Box",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 5,
    category: "Biscuits",
    requestNumber: "81P-1E",
    initiatedBy: "Approver",
    initiatedDate: "31-Jan-2020",
    product: "Cookie",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released",
    packSize: "500gm"
  },
  {
    id: 6,
    category: "Dairy",
    packSize: "500ml",
    requestNumber: "81P-1F",
    initiatedBy: "Designer",
    initiatedDate: "25-Jul-2020",
    product: "Milk",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 7,
    category: "Sauce",
    packSize: "1 Ltr",
    requestNumber: "81P-1G",
    initiatedBy: "Designer",
    initiatedDate: "21-Sept-2020",
    product: "Ketchup",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 8,
    category: "Biscuits",
    requestNumber: "81P-1H",
    initiatedBy: "Approver",
    initiatedDate: "22-Jul-2020",
    product: "Cookie",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released",
    packSize: "900g"
  },
  {
    id: 9,
    category: "Dairy",
    packSize: "500ml",
    requestNumber: "81P-1I",
    initiatedBy: "Designer",
    initiatedDate: "12-Jun-2020",
    product: "Milk",
    componentType: "Box Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 10,
    category: "Sauce",
    packSize: "1 Ltr",
    requestNumber: "81P-1J",
    initiatedBy: "Designer",
    initiatedDate: "30-Jul-2020",
    product: "Ketchup",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 11,
    category: "Biscuits",
    requestNumber: "81P-1K",
    initiatedBy: "Approver",
    initiatedDate: "21-Jul-2020",
    product: "Cookie",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released",
    packSize: "120g"
  },
  {
    id: 12,
    category: "Dairy",
    packSize: "500ml",
    requestNumber: "81P-1L",
    initiatedBy: "Designer",
    initiatedDate: "02-Aug-2020",
    product: "Milk",
    componentType: "Box",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 13,
    category: "Sauce",
    packSize: "1 Ltr",
    requestNumber: "81P-1M",
    initiatedBy: "Designer",
    initiatedDate: "20-Jul-2020",
    product: "Ketchup",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 14,
    category: "Biscuits",
    requestNumber: "81P-1N",
    initiatedBy: "Approver",
    initiatedDate: "13-Jul-2020",
    product: "Cookie",
    componentType: "Box",
    img: "artwork",
    status: "Artwork Approved and Released",
    packSize: "100g"
  },
  {
    id: 15,
    category: "Dairy",
    packSize: "500ml",
    requestNumber: "81P-1O",
    initiatedBy: "Designer",
    initiatedDate: "14-Jul-2020",
    product: "Milk",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 16,
    category: "Sauce",
    packSize: "1 Ltr",
    requestNumber: "81P-1P",
    initiatedBy: "Designer",
    initiatedDate: "16-Mar-2020",
    product: "Ketchup",
    componentType: "Box",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 17,
    category: "Dairy",
    packSize: "200gm",
    requestNumber: "81P-1Q",
    initiatedBy: "Approver",
    initiatedDate: "11-Jul-2020",
    product: "Butter",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 18,
    category: "Biscuits",
    requestNumber: "81P-1R",
    initiatedBy: "Designer",
    initiatedDate: "02-Feb-2020",
    product: "Cookie",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released",
    packSize: "100g"
  },
  {
    id: 19,
    category: "Dairy",
    packSize: "500ml",
    requestNumber: "81P-1S",
    initiatedBy: "Designer",
    initiatedDate: "06-Jul-2020",
    product: "Milk",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 20,
    category: "Dairy",
    packSize: "200gm",
    requestNumber: "81P-1T",
    initiatedBy: "Approver",
    initiatedDate: "17-Jul-2020",
    product: "Butter",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 21,
    category: "Biscuits",
    requestNumber: "81P-1U",
    initiatedBy: "Designer",
    initiatedDate: "15-Jan-2020",
    product: "Cookie",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released",
    packSize: "100g"
  },
  {
    id: 22,
    category: "Snacks",
    packSize: "500gm",
    requestNumber: "81P-1V",
    initiatedBy: "Designer",
    initiatedDate: "18-Jul-2020",
    product: "Maggie",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 23,
    category: "Dairy",
    packSize: "500ml",
    requestNumber: "81P-1W",
    initiatedBy: "Approver",
    initiatedDate: "28-Jul-2020",
    product: "Milk",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 24,
    category: "Dairy",
    packSize: "200gm",
    requestNumber: "81P-1X",
    initiatedBy: "Designer",
    initiatedDate: "16-Apr-2020",
    product: "Butter",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  },
  {
    id: 25,
    category: "Biscuits",
    requestNumber: "81P-1Y",
    initiatedBy: "Approver",
    initiatedDate: "18-May-2020",
    product: "Cookie",
    componentType: "Front Label",
    img: "artwork",
    status: "Artwork Approved and Released",
    packSize: "200gm"
  },
  {
    id: 26,
    category: "Snacks",
    packSize: "500gm",
    requestNumber: "81P-1Z",
    initiatedBy: "Designer",
    initiatedDate: "09-Jun-2020",
    product: "Maggie",
    componentType: "Back Label",
    img: "artwork",
    status: "Artwork Approved and Released"
  }
];